# Generated by Django 5.2 on 2025-04-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('addresse', models.CharField(max_length=255)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('classe', models.CharField(max_length=5)),
            ],
        ),
    ]
